GET https://stewartcse341node.onrender.com/contacts

###

GET https://stewartcse341node.onrender.com/contacts/632f72f614362e2dee554288

###

GET http://localhost:3000/contacts

###

GET http://localhost:3000/contacts/632f72f614362e2dee554288

###

POST http://localhost:3000/contacts HTTP/1.1 
Content-Type: application/json

{
    "firstName":"Levi",
    "lastName":"Parsons",
    "email":"levi.parsons@gmail.com",
    "favoriteColor":"Red",
    "birthday":"1999-09-26"
}


###

PUT http://localhost:3000/contacts/632f72f614362e2dee554288 HTTP/1.1 
Content-Type: application/json

{
    "firstName":"Emily",
    "lastName":"Rowley",
    "email":"emily.hepworth@gmail.com",
    "favoriteColor":"Purple",
    "birthday":"1998-06-30"
}


###

DELETE http://localhost:3000/contacts/633629e324f5bc1c8de53d7f HTTP/1.1 
Content-Type: application/json

###

POST https://stewartcse341node.onrender.com/contacts HTTP/1.1 
Content-Type: application/json

{
    "firstName":"Levi",
    "lastName":"Parsons",
    "email":"levi.parsons@gmail.com",
    "favoriteColor":"Red",
    "birthday":"1999-09-26"
}


###

PUT https://stewartcse341node.onrender.com/contacts/632f72f614362e2dee554288 HTTP/1.1 
Content-Type: application/json

{
    "firstName":"Emily",
    "lastName":"Rowley",
    "email":"emily.hepworth@gmail.com",
    "favoriteColor":"Green",
    "birthday":"1998-06-30"
}


###

DELETE https://stewartcse341node.onrender.com/contacts/63362ef0d59427ead7cd0eed HTTP/1.1 
Content-Type: application/json

